# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"
APP_NAME = 'rails-test'

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder "./example-rails-app", "/myapp"
  config.vm.define APP_NAME do |db|
    db.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = "../docker-host-vm/Vagrantfile"
      d.remains_running = true
      d.name = APP_NAME
      d.ports = ["3000:3000"]
      d.build_dir = "."
      # d.image = "centos:latest"
    end
  end
end
