# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define 'docker_host_vm' do |node|

    node.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = __FILE__.sub(%r{rails-test/Vagrantfile$},'docker-host-vm/VagrantFile')
      d.build_dir = "."
      d.remains_running = true
      d.name = 'rails_container'
      d.ports = ['3000:3000']
    end

  end

end
