# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    #d.image   = "nginx"
    d.ports = ["8080:80"]
    d.vagrant_vagrantfile = "../docker-host-vm/Vagrantfile"
    d.build_dir = "."
  end
end
