# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define 'database' do |db|

    db.vm.provider "docker" do |d|
      d.image="mysql:latest"
      d.env = {
        # :MYSQL_ROOT_PASSWORD => "root",
        # :MYSQL_DATABASE     => "dockertest",
        # :MYSQL_USER         => "dockertest",
        # :MYSQL_PASSWORD     => "d0cker"
        :MYSQL_ALLOW_EMPTY_PASSWORD => true
      }
      d.vagrant_vagrantfile = __FILE__.sub(%r{mysql/Vagrantfile$},'docker-host-vm/VagrantFile')
      d.remains_running = true
      d.name = 'mysql_container'
      d.ports = ["3306:3306"]
    end
  end
end
